name: List S3 Buckets
on:
  push:
    branches:
      - main  # Adjust this based on your branch naming

jobs:
  list-s3-buckets:
    runs-on: ubuntu-latest
   steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::179859935027:role/GlueRole #change to reflect your IAM role’s ARN
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity 

      
